package servlet;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

@WebServlet("/WriterHeaderBingo")
public class BingoServlet extends HttpServlet{
	private String user,sala,perfil;
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	protected void doGet(HttpServletRequest req, HttpServletResponse res) throws ServletException, IOException {
		String url="Portal.jsp";
		HttpSession mySession = req.getSession(false);
		if(mySession!=null){
			System.out.println("la mySesion "+ mySession.getId());
			//Comprobacion de HttpSession registrada aqui
			
			user = req.getParameter("usuario");//
			if(mySession.getAttribute("usuario")==null) res.sendRedirect(url); //logged-in page // 
			sala = req.getParameter("sala");
			perfil =req.getParameter("perfil");
			
		}else{
			System.out.print("la sesion es null");
	        
	        res.sendRedirect(url); //logged-in page // 
	        return;
		}

		res.setContentType("text/html; charset=utf-8");
		
		PrintWriter out;
		out = res.getWriter();
		//Html Head
	      out.write("\r\n");
	      out.write("\r\n");
	      out.write("\r\n");
	      out.write('\r');
	      out.write('\n');
	      out.write('\r');
	      out.write('\n');
	      out.write("\r\n");
	      out.write("<!doctype html>\r\n");
	      out.write("<html>\r\n");
	      out.write("<head>\r\n");
	      out.write("<meta charset=\"utf-8\">\r\n");
	      out.write("<meta name=\"vieport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
	      out.write("<title>Bingo 2016</title>\r\n");
	      out.write(" \r\n");
	      out.write("  <link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css\">\r\n");
	      out.write("  \r\n");
	      out.write("  <script src=\"//code.jquery.com/jquery-1.10.2.js\"></script>\r\n");
	      out.write("  <script src=\"//code.jquery.com/ui/1.11.4/jquery-ui.js\"></script>\r\n");
	      out.write("  \r\n");
	      out.write("<script src=\"javascript/reproductor.js\"></script>\r\n");
	      out.write("\r\n");
	      out.write("<link href=\"css/Bingo.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
	      out.write("</head>\r\n");
	      out.write("\r\n");

		
		//HTML body
	      out.write("<body class=\"pagina\" id=\"content\">\r\n");			      
	      out.write("\r\n");
	      out.write("<div id=\"agrupar\">\r\n");
	      out.write("<header id=\"cabecera\">\r\n");
	      out.write("\r\n");
	      out.write("<table width=\"100%\" border=\"1\" cellspacing=\"2\" class=\"ano\">");
	      out.write("  <tr>");
	      out.write("    <td padding=0 width=\"12%\"><a href=Portal.jsp><img id=\"logo\" src=\"images/IconoBola.jpg\" width=\"56\" height=\"45\" longdesc=\"file:///C|/Users/boga/git/wildfly/src/main/webapp/images/IconoBola.jpg\" ></a><label id=\"sala\">");
	      out.print(sala);
	      out.write("</label>\r\n");
	      out.print("<label class=\"labelUser\">"+user+"</label>");
	      out.write("</td>");
	      out.write("    <td width=\"68%\" class=\"ano\" >! BINGO 2018 ¡<nav id=\"menu\">\r\n");
	      out.write("    <label id=\"iniciar\" CLASS=\"menu_li\" >INICIAR</label>\r\n");
	      out.write("    <label id=\"resume\" CLASS=\"menu_li\" >RESUMIR</label>\r\n");
	      out.write("\t<label id=\"lab_cartones\" CLASS=\"menu_li\" >CARTONES</label>\r\n");
	      out.write("\t<label id=\"finalizar\" CLASS=\"menu_li\" >FINALIZAR</label>\r\n");
	      out.write("\t<label id=\"preferencias\" CLASS=\"menu_li\" >OPCIONES</label>\t\r\n");
	      out.write("\t</nav>\r\n");
	      out.write("\t</td>\r\n");
	      out.write("    <td id=\"CajaDcha\" width=\"20%\">2016</td>\r\n");
	      out.write("  </tr>\r\n");
	      out.write("   \r\n");
	      out.write("</table>\r\n");
	      out.write("</header>\r\n");
	      out.write("\r\n");
	      out.write("<table class=\"tablero\">\r\n");
	      out.write("    <tr>\r\n");
	      out.write("         <td class=\"panel\"> \r\n");
	      out.write("            <label class=\"numeros\" ></label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"10\" class=\"numeros\" >10</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"20\" class=\"numeros\" >20</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"30\" class=\"numeros\" >30</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"40\" class=\"numeros\" >40</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td rowspan=\"10\" class=\"panel\" > \r\n");
	      out.write("            <article class=\"Comander\" >\r\n");
	      out.write("             <span >\r\n");
	      out.write("\t\t\t <div id=\"my_poster\"> \t\r\n");
	      out.write("              <video id=\"medio\" class=\"fotom\" preload=\"auto\" >\r\n");
	      out.write("   \t\t    <source src=\"http://boga.esy.es/video/BingoInes.mov\" type=\"video/mp4\">\r\n");
	      out.write("   \t\t    <source src=\"http://boga.esy.es/video/BingoInes.ogv\" type=\"video/ogg\">\r\n");
	      out.write("\t\t\t<source src=\"http://boga.esy.es/video/BingoInes.webm\" type=\"video/webm\" >\r\n");
	      out.write("   \t         HTML5 video is not supported by this browser \r\n");
	      out.write("   \t         </video>\r\n");
	      out.write("   \t         </div>\r\n");
	      out.write("            </span>\r\n");
	      out.write("              <table   align=\"center\" class=\"tablaInfo\">\r\n");
	      out.write("     \t\t<tr>\r\n");
	      out.write("\t        <td width=\"26%\" class=\"celdaInfo\"><span class=\"Comander\"><span class=\"Comander\">BOLA N:</span></span></td>\r\n");
	      out.write("\t        <td width=\"4%\" id=\"datoOrdenBola\" class=\"celdaInfo\"  ><span class=\"Comander\"><span class=\"Comander\">\r\n");
	      out.write("\t          <label id=\"labelOrden\" class=\"valorInfo\">0</label>\r\n");
	      out.write("\t        </span></span></td>\r\n");
	      out.write("\t        <td width=\"37%\" id=\"datoLinea\" class=\"celdaInfo\" ><label id=\"labelLinea\">LINEA:</label></td>\r\n");
	      out.write("\t        <td width=\"33%\" class=\"celdaInfo\"><span class=\"Comander\"><span class=\"Comander\">\r\n");
	      out.write("\t          <label id=\"valorLinea\" class=\"valorInfo\">0 €</label>\r\n");
	      out.write("\t        </span></span></td>\r\n");
	      out.write("\t        </tr>\r\n");
	      out.write("\t      <tr>\r\n");
	      out.write("\t        <td class=\"celdaInfo\"><span class=\"Comander\"><span class=\"Comander\"> CARTONES</span></span></td>\r\n");
	      out.write("\t        <td id=\"datoCartones\" class=\"celdaInfo\" ><span class=\"Comander\"><span class=\"Comander\">\r\n");
	      out.write("\t          <label id=\"valorCartones\" class=\"valorInfo\">0</label>\r\n");
	      out.write("\t        </span></span></td>\r\n");
	      out.write("\t        <td class=\"celdaInfo\"><label id=\"labelBingo\">BINGO:</label></td>\r\n");
	      out.write("\t        <td  id=\"datoBingo\" class=\"celdaInfo\" ><span class=\"Comander\"><span class=\"Comander\">\r\n");
	      out.write("\t          <label id=\"valorBingo\" class=\"valorInfo\">0 €</label>\r\n");
	      out.write("\t        </span></span></td>\r\n");
	      out.write("    </tr>\r\n");
	      out.write("\t      <tr>\r\n");
	      out.write("\t        <td colspan=\"4\"  class=\"celdaInfo\" id=\"comboTexto\" >\r\n");
	      out.write("\t          \r\n");
	      out.write("\t          <label  id=\"labelTexto\" class=\"classMessage\" >combotexto</label>\r\n");
	      out.write("\t         \r\n");
	      out.write("\t        \r\n");
	      out.write("    \t</tr>\r\n");
	      out.write("</table>\r\n");
	      out.write("\t\r\n");
	      out.write("\t          <span class=\"Comander\"><span class=\"Comander\">\r\n");
	      out.write("\t          <canvas id=\"canvas_bola\" class=\"canvasBola\">\r\n");
	      out.write("\t           \r\n");
	      out.write("              </canvas>\r\n");
	      out.write("\t\r\n");
	      out.write("        </span></span></article>      \r\n");
	      out.write("             \r\n");
	      out.write("      </td>\r\n");
	      out.write("      <td class=\"panel\">\r\n");
	      out.write("      \t<label id=\"50\" class=\"numeros\" >50</label>\r\n");
	      out.write("      </td >\r\n");
	      out.write("      <td class=\"panel\">\r\n");
	      out.write("            <label id=\"60\" class=\"numeros\" >60</label>              \r\n");
	      out.write("     </td >\r\n");
	      out.write("\r\n");
	      out.write("        <td class=\"panel\">\r\n");
	      out.write("            <label id=\"70\" class=\"numeros\" >70</label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("        <td class=\"panel\">\r\n");
	      out.write("            <label id=\"80\" class=\"numeros\" >80</label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("\r\n");
	      out.write("        <td class=\"panel\">\r\n");
	      out.write("            <label id=\"90\" class=\"numeros\" >90</label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("\r\n");
	      out.write("  </tr>\r\n");
	      out.write("    <tr>\r\n");
	      out.write("       <td class=\"panel\">\r\n");
	      out.write("         <label id=\"1\" class=\"numeros\" >01</label>\r\n");
	      out.write("       </td>\r\n");
	      out.write("               <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"11\" class=\"numeros\" >11</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"21\" class=\"numeros\" >21</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"31\" class=\"numeros\" >31</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"41\" class=\"numeros\" >41</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"51\" class=\"numeros\" >51</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"61\" class=\"numeros\" >61</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("    \r\n");
	      out.write("        <td class=\"panel\">\r\n");
	      out.write("            <label id=\"71\" class=\"numeros\" >71</label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("        <td class=\"panel\">\r\n");
	      out.write("            <label id=\"81\" class=\"numeros\" >81</label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("\t\t<td class=\"panel\">\r\n");
	      out.write("            <label class=\"numeros\" ></label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("  </tr>\r\n");
	      out.write("\r\n");
	      out.write("  <tr>\r\n");
	      out.write("         <td class=\"panel\"><label id=\"2\" class=\"numeros\" >02</label></td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"12\" class=\"numeros\" >12</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"22\" class=\"numeros\" >22</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"32\" class=\"numeros\" >32</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"42\" class=\"numeros\" >42</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"52\" class=\"numeros\" >52</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"62\" class=\"numeros\" >62</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("    \r\n");
	      out.write("        <td class=\"panel\">\r\n");
	      out.write("            <label id=\"72\" class=\"numeros\" >72</label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("        <td class=\"panel\">\r\n");
	      out.write("            <label id=\"82\" class=\"numeros\" >82</label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("<td class=\"panel\">\r\n");
	      out.write("            <label class=\"numeros\" ></label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("  </tr>\r\n");
	      out.write("  <tr>\r\n");
	      out.write("         <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"3\" class=\"numeros\" >03</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"13\" class=\"numeros\" >13</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"23\" class=\"numeros\" >23</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"33\" class=\"numeros\" >33</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"43\" class=\"numeros\" >43</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      \r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"53\" class=\"numeros\" >53</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"63\" class=\"numeros\" >63</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("    \r\n");
	      out.write("        <td class=\"panel\">\r\n");
	      out.write("            <label id=\"73\" class=\"numeros\" >73</label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("        <td class=\"panel\">\r\n");
	      out.write("            <label id=\"83\" class=\"numeros\" >83</label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("<td class=\"panel\">\r\n");
	      out.write("            <label class=\"numeros\" ></label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("  </tr>\r\n");
	      out.write("  <tr>\r\n");
	      out.write("         <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"4\" class=\"numeros\" >04</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"14\" class=\"numeros\" >14</label>             \r\n");
	      out.write("      </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"24\" class=\"numeros\" >24</label>             \r\n");
	      out.write("      </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"34\" class=\"numeros\" >34</label>             \r\n");
	      out.write("      </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"44\" class=\"numeros\" >44</label>             \r\n");
	      out.write("      </td>\r\n");
	      out.write("      \r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"54\" class=\"numeros\" >54</label>             \r\n");
	      out.write("      </td>\r\n");
	      out.write("    \r\n");
	      out.write("        <td class=\"panel\">\r\n");
	      out.write("            <label id=\"64\" class=\"numeros\" >64</label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("        <td class=\"panel\">\r\n");
	      out.write("            <label id=\"74\" class=\"numeros\" >74</label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("\t<td class=\"panel\">\r\n");
	      out.write("            <label id=\"84\" class=\"numeros\" >84</label>              \r\n");
	      out.write("      </td >\r\n");
	      out.write("        <td class=\"panel\">\r\n");
	      out.write("            <label class=\"numeros\" ></label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("  </tr>\r\n");
	      out.write("  <tr>\r\n");
	      out.write("         <td class=\"panel\"><label id=\"5\" class=\"numeros\" >05</label></td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"15\" class=\"numeros\" >15</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"25\" class=\"numeros\" >25</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"35\" class=\"numeros\" >35</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"45\" class=\"numeros\" >45</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      \r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"55\" class=\"numeros\" >55</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("    \r\n");
	      out.write("        <td class=\"panel\">\r\n");
	      out.write("            <label id=\"65\" class=\"numeros\" >65</label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("        <td class=\"panel\">\r\n");
	      out.write("            <label id=\"75\" class=\"numeros\" >75</label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("\t\t<td class=\"panel\">\r\n");
	      out.write("            <label id=\"85\" class=\"numeros\" >85</label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("        <td class=\"panel\">\r\n");
	      out.write("            <label class=\"numeros\" ></label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("  </tr>\r\n");
	      out.write("  <tr>\r\n");
	      out.write("         <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"6\" class=\"numeros\" >06</label>\r\n");
	      out.write("            </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"16\" class=\"numeros\" >16</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"26\" class=\"numeros\" >26</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"36\" class=\"numeros\" >36</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"46\" class=\"numeros\" >46</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      \r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"56\" class=\"numeros\" >56</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("    \r\n");
	      out.write("        <td class=\"panel\">\r\n");
	      out.write("            <label id=\"66\" class=\"numeros\" >66</label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("        <td class=\"panel\">\r\n");
	      out.write("            <label id=\"76\" class=\"numeros\" >76</label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("\t\t<td class=\"panel\">\r\n");
	      out.write("            <label id=\"86\" class=\"numeros\" >86</label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("        <td class=\"panel\">\r\n");
	      out.write("            <label class=\"numeros\" ></label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("  </tr>\r\n");
	      out.write("  <tr>\r\n");
	      out.write("         <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"7\" class=\"numeros\" >07</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"17\" class=\"numeros\" >17</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"27\" class=\"numeros\" >27</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"37\" class=\"numeros\" >37</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"47\" class=\"numeros\" >47</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      \r\n");
	      out.write("      \t<td class=\"panel\"> \r\n");
	      out.write("            <label id=\"57\" class=\"numeros\" >57</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("    \r\n");
	      out.write("        <td class=\"panel\">\r\n");
	      out.write("            <label id=\"67\" class=\"numeros\" >67</label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("        <td class=\"panel\">\r\n");
	      out.write("            <label id=\"77\" class=\"numeros\" >77</label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("\t\t<td class=\"panel\">\r\n");
	      out.write("            <label id=\"87\" class=\"numeros\" >87</label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("        <td class=\"panel\">\r\n");
	      out.write("            <label class=\"numeros\" ></label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("  </tr>\r\n");
	      out.write("  <tr>\r\n");
	      out.write("         <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"8\" class=\"numeros\" >08</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"18\" class=\"numeros\" >18</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"28\" class=\"numeros\" >28</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"38\" class=\"numeros\" >38</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"48\" class=\"numeros\" >48</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      \r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"58\" class=\"numeros\" >58</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("    \r\n");
	      out.write("        <td class=\"panel\">\r\n");
	      out.write("            <label id=\"68\" class=\"numeros\" >68</label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("        <td class=\"panel\">\r\n");
	      out.write("            <label id=\"78\" class=\"numeros\" >78</label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("\t\t<td class=\"panel\">\r\n");
	      out.write("            <label id=\"88\" class=\"numeros\" >88</label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("        <td class=\"panel\">\r\n");
	      out.write("            <label class=\"numeros\" ></label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("  </tr>\r\n");
	      out.write("  <tr>\r\n");
	      out.write("         <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"9\" class=\"numeros\" >09</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"19\" class=\"numeros\" >19</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"29\" class=\"numeros\" >29</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"39\" class=\"numeros\" >39</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      <td class=\"panel\"> \r\n");
	      out.write("            <label id=\"49\" class=\"numeros\" >49</label>             \r\n");
	      out.write("        </td>\r\n");
	      out.write("      \r\n");
	      out.write("      <td class=\"panel\">\r\n");
	      out.write("          <label id=\"59\" class=\"numeros\" >59</label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("        <td class=\"panel\">\r\n");
	      out.write("            <label id=\"69\" class=\"numeros\" >69</label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("\t\t<td class=\"panel\">\r\n");
	      out.write("            <label id=\"79\" class=\"numeros\" >79</label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("        <td class=\"panel\">\r\n");
	      out.write("            <label id=\"89\" class=\"numeros\" >89</label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("        <td class=\"panel\">\r\n");
	      out.write("            <label class=\"numeros\" ></label>              \r\n");
	      out.write("        </td >\r\n");
	      out.write("  </tr>\r\n");
	      out.write("</table>\r\n");
	      out.write("\r\n");
	      out.write(" \r\n");
	      out.write("\r\n");
	      out.write("\r\n");
	      out.write("<article id=\"articulo\">\t\r\n");
	      out.write("<div align=\"center\">  \r\n");
	      out.write(" \r\n");
	      out.write("<label id=\"play\" CLASS=\"menu_li2\" >PLAY</label>\r\n");
	      out.write("<label id=\"pause\" CLASS=\"menu_li2\" >PAUSE</label>\r\n");
	      out.write("<label id=\"boton_Linea\" CLASS=\"menu_li2\" >LINEA</label>\r\n");
	      out.write("<label id=\"boton_Bingo\" CLASS=\"menu_li2\" >BINGO</label>\r\n");
	      out.write("<label id=\"boton_LineaOk\" CLASS=\"menu_li2\" >LINEA OK</label>\r\n");
	      out.write("<label id=\"boton_BingoOk\" CLASS=\"menu_li2\" >BINGO OK</label>\r\n");
	      out.write("<label id=\"boton_Continuar\" CLASS=\"menu_li2\" >CONTINUAR</label>\r\n");
	      out.write("</div>  \r\n");
	      out.write("</article>\r\n");
	      out.write("</div>\r\n");
	      out.write("<article>\r\n");
	      out.write("\r\n");
	      out.write("<p><label id=\"foot\"> BINGO 2018</label>></p>    \r\n");
	      out.write("\r\n");
	      out.write("\r\n");
	      out.write("\r\n");
	      out.write("<footer>\r\n");
	      out.write("  <div class=\"Comander2\">\r\n");
	      out.write("  \r\n");
	      out.write("    <input type=\"submit\" name=\"comando\" id=\"comando\" value=\"Enviar\">\r\n");
	      out.write("    <label for=\"text_comando\"></label>\r\n");
	      out.write("    <input type=\"text\" name=\"text_comando\" id=\"text_comando\">\r\n");
	      out.write("    <input type=\"button\" id=\"notify\">\r\n");
	      out.write("      \r\n");
	      out.write("<input type=\"hidden\" id=\"sala\" name=\"sala\" value=\"");
	out.print(sala); 
	      out.write("\">\r\n");
	      out.write("<input type=\"hidden\" id=\"usuario\"  name=\"usuario\" value=\"");
	out.print(user); 
	      out.write("\">\r\n");
	      out.write("<input type=\"hidden\" id=\"perfil\"  name=\"perfil\" value=\"");
	out.print(perfil); 
	      out.write("\">\r\n");	      
	      out.write("      \r\n");
	      out.write("\t  <input type=\"text\" id=\"seek_ini\" value=\"00:00\" size=\"20\">\r\n");
	      out.write("\t  \r\n");
	      out.write("      \r\n");
	      out.write("\t  <input type=\"text\" id=\"seek_fin\" value=\"00:00\">\r\n");
	      out.write("\t  \r\n");
	      out.write("\t  \r\n");
	      out.write("\t  <input type=\"text\" id=\"contador\" value=\"00:00\">\r\n");
	      out.write("\t  \r\n");
	      out.write("\t  \r\n");
	      out.write("\t    <input id=\"c_Range\" value=\"Play Range\" type=\"button\">\r\n");
	      out.write("   \t  \r\n");
	      out.write("  </div>   \r\n");
	      out.write("  \r\n");
	      out.write("</footer>\r\n");
	      out.write("\r\n");
	      out.write("\r\n");
	      out.write("<div id=\"opciones\" title=\"Preferencias\">\r\n");
	      out.write("\r\n");
	      out.write("ELEGIR CANTAOR\r\n");
	      out.write("<select name=\"cantaor\">\r\n");
	      out.write("<option value=\"0\">Seleccione un cantaor</option>\r\n");
	      out.write("<!--<option value=\"Lola\">Lola (velocida Lenta)</option>-->\r\n");
	      out.write("\t<option value=\"Ines\">Ines (velocida Rapida)<option>\r\n");
	      out.write("</select>\r\n");
	      out.write("<p>&nbsp;\r\n");
	      out.write("</p>\r\n");
	      out.write("<form > \r\n");
	      out.write("  <table width=\"200\">\r\n");
	      out.write("    <tr>\r\n");
	      out.write("      <td><label>\r\n");
	      out.write("        <input type=\"radio\" name=\"Codecs\" value=\"MP4\" id=\"Codecs_0\">\r\n");
	      out.write("        MP4</label></td>\r\n");
	      out.write("    </tr>\r\n");
	      out.write("    <tr>\r\n");
	      out.write("      <td><label>\r\n");
	      out.write("        <input type=\"radio\" name=\"Codecs\" value=\"OGG\" id=\"Codecs_1\">\r\n");
	      out.write("        OGG</label></td>\r\n");
	      out.write("    </tr>\r\n");
	      out.write("    <tr>\r\n");
	      out.write("      <td><label>\r\n");
	      out.write("        <input type=\"radio\" name=\"Codecs\" value=\"WEBM\" id=\"Codecs_2\"  checked>\r\n");
	      out.write("        WebM</label></td>\r\n");
	      out.write("    </tr>\r\n");
	      out.write("  </table>\r\n");
	      out.write("</form>\r\n");
	      out.write("<p>\r\n");
	      out.write("  <input name=\"videoON\" type=\"checkbox\" value=\"true\" checked>Activar Video\r\n");
	      out.write("</p>\r\n");
	      out.write("<p><input name=\"starsON\" type=\"checkbox\" value=\"true\" checked>Activar StartsField\r\n");
	      out.write("</p>\r\n");
	      out.write("\r\n");
	      out.write("<hr width=\"75%\"/>\r\n");
	      out.write("\r\n");
	      out.write("<label>Tamano Maximo numeros</label>\r\n");
	      out.write("<div id=\"slider\"></div>\r\n");
	      out.write("<p>\r\n");
	      out.write("<input type=\"text\" id=\"maxTamano\">\r\n");
	      out.write("<input type=\"button\" id=\"aplicarSize\" value=\"Aplicar Tamaño\">\r\n");
	      out.write("<hr width=\"75%\"/>\r\n");
	      out.write("<input type=\"text\" id=\"delay\" value=\"0\">\r\n");
	      out.write("<input type=\"button\" id=\"aplicarDelay\" value=\"Aplicar Delay\">\r\n");
	      out.write("</div>\r\n");
	      out.write("\r\n");
	      out.write("<div id=\"cartones\" title=\"Configuracion cartones\"> \r\n");
	      out.write("<form>\r\n");
	      out.write("<label >Precio Carton(€):</label><input type=\"text\" id=\"PrecioCarton\">\r\n");
	      out.write("<br>\r\n");
	      out.write("<label >N: Cartones en Juego:</label><input type=\"text\"  id=\"NCartonesJuego\">\r\n");
	      out.write("<br>\r\n");
	      out.write("<label >N: Cartones Manuales:</label><input type=\"text\" id=\"NCartonesManuales\">\r\n");
	      out.write("<br>\r\n");
	      out.write("<label >Asignacion % Premio Linea:</label><input type=\"text\" id=\"porcientoLinea\">\r\n");
	      out.write("<br>\r\n");
	      out.write("<label >Asignacion % Premio Bingo:</label><input type=\"text\" id=\"porcientoBingo\">\r\n");
	      out.write("<br>\r\n");
	      out.write("<label >Asignacion % Cantaor     :</label><input type=\"text\" id=\"porcientoCantaor\">\r\n");
	      out.write("\r\n");
	      out.write("</form>\r\n");
	      out.write("</div>\r\n");
	      out.write("<div id=\"premiosForm\" title=\"- Comprobacion cartones -\">\r\n");
	      out.write("<form id=\"requestPremios\">\r\n");
	      out.write("\r\n");
	      out.write("<label>Numero de carton premiado?</label>\r\n");
	      out.write("<br>\r\n");
	      out.write("<input id=\"spinner_centenas\" type=\"text\" value=\"1\" name=\"nSpin1\" style=\" width : 27px;\">\r\n");
	      out.write("<input id=\"spinner_decenas\" type=\"text\" value=\"1\" name=\"nSpin2\" style=\" width : 27px;\">\r\n");
	      out.write("<input id=\"spinner_unidades\" type=\"text\"  value=\"1\" name=\"nSpin3\" style=\" width : 27px;\">\r\n");
	      out.write("<input type=\"hidden\" id=\"nRef\" name=\"nRef\" value=\"0\">\r\n");
	      out.write("<input type=\"hidden\" id=\"comandoHandshake\" name=\"comandoHandshake\" value=\"\">\r\n");
	      out.write("<input type=\"hidden\" id=\"sala\" name=\"sala\" value=\"");
	out.print(sala); 
	      out.write("\">\r\n");
	      out.write("<input type=\"hidden\" id=\"usuario\"  name=\"usuario\" value=\"");
	out.print(user); 
	      out.write("\">\r\n");
	      out.write("<br>\r\n");
	      out.write("<label id=\"feedback\" style=\" width : 100%;\"></label>\r\n");
	      out.write("</form>\r\n");
	      out.write("</div>\r\n");
	      out.write("\r\n");
	      out.write("\r\n");
	      out.write("\r\n");	      
	      out.write("<audio id=\"audioWeb\">\r\n");
	      out.write("  \t<source src=\"http://boga.esy.es/audio/AudioLinea1.mp3\" type=\"audio/mpeg\">\r\n");
	      out.write("\tYour browser does not support the audio element.\r\n");
	      out.write("</audio>\r\n");
	      out.write("\r\n");
	      out.write("</body>\r\n");
	      out.write("\r\n");
	      out.write("</html>\r\n");	      
	}
  
}
